# .streamlit/config.toml (Tema Profissional Dark)
[theme]
# Cor primária de destaque (botões, etc.) - Nosso Azul Royal
primaryColor="#3B82F6"

# Fundo principal da aplicação
backgroundColor="#0F172A" # Um azul-escuro/quase preto corporativo

# Fundo para elementos como a barra lateral e caixas
secondaryBackgroundColor="#1E293B"

# Cor principal do texto
textColor="#FFFFFF"

# Fonte padrão do Streamlit
font="sans serif"
