[server]
headless = true
port = 8501
enableCORS = false

[runner]
# Streamlit lê o Python do ambiente, mas esta é uma boa prática
# para documentar a versão alvo do ambiente de desenvolvimento.
python = "3.11"